services:
  - type: worker
    name: recon-worker
    env: docker
    plan: free
    autoDeploy: false
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_HOST
        sync: false
      - key: PROJECT_NAME
        sync: false
